module.exports = {
  CDON_APIURL: process.env.CDON_API_URL,
  CDON_APIKEY: process.env.CDON_APIKEY,
  CDON_ADDRESSID: process.env.CDON_ADDRESSID,
  ONGOING_APIURL: process.env.ONGOING_APIURL,
  ONGOING_GOODSOWNERID: process.env.ONGOING_GOODSOWNERID,
  ONGOING_USERNAME: process.env.ONGOING_GOODSOWNERID,
  ONGOING_PASSWORD: process.env.ONGOING_PASSWORD
};
